export function helpText(): string {
  return [
    'Usage:',
    '  english-pilot check --text "I want to create a new project" [--json]',
    '  english-pilot check "I want to create a new project" [--json]',
    '  english-pilot check --stdin [--json]',
    '  english-pilot hook claude|codex --stdin',
    '  english-pilot setup [--yes] [--agent off|claude|codex] [--cwd <path>] [--json]',
    '  english-pilot install targets [--json]',
    '  english-pilot install claude|codex --dry-run | --yes',
    '  english-pilot uninstall claude|codex --yes',
    '  english-pilot run [--dry-run] [--json]',
    '  english-pilot daemon status [--json]',
    '  english-pilot service install [--dry-run] [--json]',
    '  english-pilot service install-dev [--dry-run] [--json]',
    '  english-pilot service uninstall|status|restart|logs|pause|resume',
    '  english-pilot config get',
    '  english-pilot config profiles [--json]',
    '  english-pilot config profile-status [--json]',
    '  english-pilot config progression-suggestion [--json]',
    '  english-pilot config progression-apply [--yes] [--json]',
    '  english-pilot config use beginner|balanced|strict|force [--json]',
    '  english-pilot config set maxChineseRatio 0.3',
    '  english-pilot review [--json]',
    '  english-pilot review due [--date YYYY-MM-DD] [--json]',
    '  english-pilot review upcoming [--date YYYY-MM-DD] [--days N] [--json]',
    '  english-pilot review mark <id> again|hard|easy',
    '  english-pilot review update <id> [--original "..."] [--suggested "..."] [--scene "..."] [--pattern "..."] [--tag tag] [--json]',
    '  english-pilot review remove <id>',
    '  english-pilot review cleanup [--yes] [--json]',
    '  english-pilot coach --text "..." [--record] [--json]',
    '  english-pilot coach context [--json]',
    '  english-pilot coach templates [--scene <id>] [--record] [--json]',
    '  english-pilot pronounce --text "..." [--json]',
    '  english-pilot agent doctor [--json]',
    '  english-pilot agent run --text "..." [--backend claude|codex] [--cwd <path>] [--dry-run] [--json]',
    '  english-pilot voice providers [--json]',
    '  english-pilot voice stt-policy [--json]',
    '  english-pilot voice stt-contract [--json]',
    '  english-pilot voice stt-validate --response-json <json> | --response-json-file <path> [--json]',
    '  english-pilot voice stt-assess-provider --provider-name <name> --response-json <json> | --response-json-file <path> [--record] [--json]',
    '  english-pilot voice stt-assessment-history [--provider-name <name>] [--json]',
    '  english-pilot voice stt-provider-contract-draft --provider-name <name> [--json]',
    '  english-pilot voice stt-wrapper-template [--json]',
    '  english-pilot voice preflight --provider <provider> [--json]',
    '  english-pilot voice transcribe --provider local-whisper|cloud-stt --audio <path> [--json]',
    '  english-pilot voice practice --provider local-whisper|cloud-stt --audio <path> --target "..." [--feedback "..."] [--json]',
    '  english-pilot voice record --transcript "..." --target "..." [--feedback "..."] [--json]',
    '  english-pilot feishu setup [--json]',
    '  english-pilot feishu doctor [--json]',
    '  english-pilot feishu start [--dry-run] [--json]',
    '  english-pilot wechat setup [--json]',
    '  english-pilot wechat doctor [--json]',
    '  english-pilot wechat accounts [--json]',
    '  english-pilot wechat logout <accountId>',
    '  english-pilot wechat start [--dry-run] [--json]',
    '  english-pilot daily [--json]',
    '  english-pilot daily start [--json]',
    '  english-pilot daily answer <id> [--json]',
    '  english-pilot daily check <id> --answer "..." [--json]',
    '  english-pilot daily mark <id> again|hard|easy',
    '  english-pilot daily pack [--date YYYY-MM-DD] [--write] [--json]',
    '  english-pilot glossary list [--json]',
    '  english-pilot glossary add <term> [--ipa "..."] [--meaning "..."] [--tag tag] [--allow-term]',
    '  english-pilot glossary remove <term>',
    '  english-pilot stats [--json]',
    '  english-pilot export markdown',
    '  english-pilot export obsidian --write [--dir path]',
    '  english-pilot handoff external-validation [--target feishu|wechat|cloud-stt] [--write|--verify] [--dir <path>] [--json]',
    '  english-pilot integrations targets [--json]',
    '  english-pilot integrations daily-pack --target <target> [--date YYYY-MM-DD] [--json]',
    '  english-pilot integrations credential-policy --target <target> [--json]',
    '  english-pilot integrations delivery-mode --target <target> [--json]',
    '  english-pilot integrations dry-run --target <target> [--date YYYY-MM-DD] [--json]',
    '  english-pilot integrations preflight --target <target> [--json]',
    '  english-pilot integrations send-readiness --target wechat [--date YYYY-MM-DD] [--confirm-send] [--json]',
    '  english-pilot integrations send --target wechat [--date YYYY-MM-DD] --send [--require-validation] [--json]',
    '  english-pilot integrations account-guide --target wechat [--json]',
    '  english-pilot integrations account-validate --target wechat [--date YYYY-MM-DD] [--send] [--record] [--json]',
    '  english-pilot integrations validation-history [--target wechat] [--json]',
    '  english-pilot integrations message-coaching --target <target> --text "..." [--record] [--json]',
    '  english-pilot integrations event-coaching --target wechat --event-json <json> [--record] [--json]',
    '  english-pilot integrations deliver --target obsidian [--date YYYY-MM-DD] [--dir <path>] [--write] [--json]',
    '  english-pilot serve --mcp',
    '  english-pilot doctor [--write] [--dir <path>] [--json]',
    '  english-pilot status [--json]',
    '  english-pilot roadmap [--target feishu|wechat|cloud-stt] [--write] [--dir <path>] [--json]',
    '  english-pilot roadmap next [--target feishu|wechat|cloud-stt] [--write] [--dir <path>] [--json]',
    '  english-pilot roadmap env-template [--target feishu|wechat|cloud-stt] [--json]',
    '  english-pilot eval smoke [--json]',
    '  english-pilot eval prompts',
    '  english-pilot eval agent --backend claude|codex [--case channel-weather] [--dry-run] [--include-raw] [--json]',
    '',
  ].join('\n');
}
