export interface ProjectStatus {
  name: 'EnglishPilot';
  version: '0.1.0';
  supported: {
    hooks: string[];
    cli: string[];
    mcp: string[];
    storage: string[];
    integrations: string[];
    voice: string[];
  };
  deferred: string[];
  planned: string[];
  openDecisions: string[];
}

export function buildProjectStatus(mcpTools: readonly string[]): ProjectStatus {
  return {
    name: 'EnglishPilot',
    version: '0.1.0',
    supported: {
      hooks: ['claude', 'codex'],
      cli: [
        'check',
        'hook',
        'install',
        'uninstall',
        'run',
        'daemon status',
        'service install',
        'service uninstall',
        'service status',
        'service restart',
        'service logs',
        'config',
        'config profiles',
        'config use',
        'config profile-status',
        'config progression-suggestion',
        'config progression-apply',
        'review',
        'review update',
        'review remove',
        'review cleanup',
        'coach',
        'coach context',
        'coach templates',
        'coach templates --record',
        'pronounce',
        'agent doctor',
        'agent run',
        'voice providers',
        'voice stt-policy',
        'voice stt-contract',
        'voice stt-validate',
        'voice stt-assess-provider',
        'voice stt-assessment-history',
        'voice stt-provider-contract-draft',
        'voice stt-wrapper-template',
        'voice preflight',
        'voice transcribe',
        'voice practice',
        'voice record',
        'daily',
        'daily check',
        'glossary',
        'stats',
        'export',
        'handoff external-validation',
        'handoff external-validation --verify',
        'feishu',
        'feishu setup',
        'feishu doctor',
        'feishu start',
        'wechat',
        'wechat setup',
        'wechat doctor',
        'wechat accounts',
        'wechat logout',
        'wechat start',
        'integrations targets',
        'integrations daily-pack',
        'integrations credential-policy',
        'integrations delivery-mode',
        'integrations dry-run',
        'integrations preflight',
        'integrations send-readiness',
        'integrations send',
        'integrations send --require-validation',
        'integrations account-guide',
        'integrations account-validate',
        'integrations validation-history',
        'integrations message-coaching',
        'integrations message-coaching --record',
        'integrations event-coaching',
        'integrations deliver',
        'doctor',
        'doctor --write',
        'serve --mcp',
        'status',
        'roadmap',
        'roadmap next',
        'roadmap --target',
        'roadmap --write',
      ],
      mcp: [...mcpTools],
      storage: ['sqlite', 'jsonl'],
      integrations: [
        'Feishu/Lark QR onboarding',
        'Feishu/Lark long-connection message coaching',
        'Feishu/Lark managed daemon runtime',
        'Feishu/Lark allowlisted sender monitoring',
        'Feishu/Lark external AgentRunner handoff',
        'Feishu/Lark conversation session resume',
        'Feishu/Lark voice-to-agent transcription',
        'WeChat QR-login onboarding',
        'WeChat long-connection message coaching',
        'WeChat managed daemon runtime',
        'WeChat allowlisted sender monitoring',
        'WeChat external AgentRunner handoff',
        'WeChat conversation thread resume',
        'WeChat voice transcript-to-agent routing',
        'WeChat long-connection reconnect and session refresh guidance',
        'WeChat payload dry-run and preflight',
        'Environment-variable credential policy',
        'Feishu/Lark long-connection delivery mode policy',
        'WeChat delivery mode policy',
        'WeChat send readiness gate',
        'WeChat network sender',
        'WeChat account-validation-gated sender',
        'WeChat account validation guide',
        'WeChat account validation playbook',
        'WeChat account validation history',
        'Feishu/Lark and WeChat message coaching payloads',
        'Feishu/Lark and WeChat recordable message coaching workflow',
        'WeChat inbound message event coaching',
        'launchd/systemd service management for external channels',
        'local daemon control socket',
      ],
      voice: [],
    },
    deferred: [
      'Obsidian/Markdown review export and daily-review delivery are implemented but parked outside the current mainline.',
      'General Voice/STT practice and pronunciation feedback are implemented but parked outside the current mainline; channel voice-to-agent routing is supported for Feishu/Lark and WeChat.',
    ],
    planned: ['Provider-specific cloud STT contract if generic-json is insufficient'],
    openDecisions: [],
  };
}
